#!/bin/bash
BASEDIR=$(cd "$(dirname "$0")"; pwd)
printf "installing scripts to ~/bin\n"

# Dev scripts:
ln -s -f -v $BASEDIR/bash/check-version.sh ~/bin/check-version
ln -s -f -v $BASEDIR/groovy/resetIntelliJLayout.groovy ~/bin/resetIntelliJLayout
ln -s -f -v $BASEDIR/groovy/xmlToClosure.groovy ~/bin/xmlToClosure
ln -s -f -v $BASEDIR/groovy/queryApp.groovy ~/bin/queryApp
ln -s -f -v $BASEDIR/bash/search-dependencies.sh ~/bin/search-dependencies
ln -s -f -v $BASEDIR/bash/buildkite.sh ~/bin/buildkite
ln -s -f -v $BASEDIR/bash/jira.sh ~/bin/jira
ln -s -f -v $BASEDIR/bash/test-report.sh ~/bin/test-report
ln -s -f -v $BASEDIR/bash/clean-target-dir.sh ~/bin/cleanTarget
ln -s -f -v $BASEDIR/bash/clean-all-targets.sh ~/bin/cleanAllTargets
ln -s -f -v $BASEDIR/bash/reset-ssh.sh ~/bin/reset-ssh
ln -s -f -v $BASEDIR/bash/intellij.sh ~/bin/intellij
ln -s -f -v $BASEDIR/bash/init-terraform.sh ~/bin/init-terraform

ln -s -f -v /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl ~/bin/sublime

ln -s -f -v $BASEDIR/bash/kill-java.sh ~/bin/kill-java

# MySQL
ln -s -f -v $BASEDIR/bash/setup-mysql-ramdisk.sh ~/bin/setup-mysql-ramdisk
ln -s -f -v $BASEDIR/bash/teardown-mysql-ramdisk.sh ~/bin/teardown-mysql-ramdisk

if [ ! -d "~/bin/lib" ]; then
	mkdir -p ~/bin/lib
fi

ln -s -f -v $BASEDIR/bash/cd-scripts.sh ~/bin/lib/cd-scripts.sh
ln -s -f -v $BASEDIR/bash/completion.sh ~/bin/lib/completion.sh
ln -s -f -v $BASEDIR/bash/docker-scripts.sh ~/bin/lib/docker-scripts.sh
ln -s -f -v $BASEDIR/bash/git-prompt.sh ~/bin/lib/git-prompt.sh
ln -s -f -v $BASEDIR/bash/git-scripts.sh ~/bin/lib/git-scripts.sh
ln -s -f -v $BASEDIR/bash/initialize-java-version.sh ~/bin/lib/initialize-java-version
ln -s -f -v $BASEDIR/bash/switch-java.sh ~/bin/lib/switch-java
ln -s -f -v $BASEDIR/bash/ssh-completion.sh ~/bin/lib/ssh-completion

# GIT scripts:
ln -s -f -v $BASEDIR/bash/git-prune-all.sh ~/bin/git-prune-all
ln -s -f -v $BASEDIR/bash/git-prune-repo.sh ~/bin/git-prune-repo
ln -s -f -v $BASEDIR/bash/git-checkout-all.sh ~/bin/git-checkout-all
ln -s -f -v $BASEDIR/bash/git-checkout-prod-version.sh ~/bin/git-checkout-prod-version
ln -s -f -v $BASEDIR/bash/hub.sh ~/bin/hub

# Private:
ROOTDIR="$(dirname "$BASEDIR")"
if [ -d "$ROOTDIR/private" ]; then
	ln -s -f -v $ROOTDIR/private/ssh-aliases.sh ~/bin/lib/ssh-aliases.sh
	$BASEDIR/groovy/generateSshConfig.groovy $ROOTDIR/private

	$BASEDIR/groovy/generateGitConfig.groovy $ROOTDIR/private

	ln -s -f -v $ROOTDIR/private/env.sh ~/bin/lib/env.sh

	ln -s -f -v $ROOTDIR/private/migrate-database.sh ~/bin/lib/migrate-database.sh

	ln -s -f -v $ROOTDIR/private/buildnet.sh ~/bin/buildnet.sh
fi

# Homebrew
if [[ -z /usr/local/bin/brew ]]; then
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

rm `brew --prefix`/etc/bash_completion.d/kubectl
brew install kubectl

brew install nvm

mkdir -v ~/.nvm
curl -o ~/.nvm/bash_completion https://raw.githubusercontent.com/creationix/nvm/master/bash_completion

# Completion
brew install bash-completion
curl -o `brew --prefix`/etc/bash_completion.d/docker https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker
curl -o `brew --prefix`/etc/bash_completion.d/docker-compose https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose
curl -o `brew --prefix`/etc/bash_completion.d/terraform https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/terraform.completion.bash
curl -o `brew --prefix`/etc/bash_completion.d/npm https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/npm.completion.bash
curl -o `brew --prefix`/etc/bash_completion.d/gradle https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/gradle.completion.bash
curl -o `brew --prefix`/etc/bash_completion.d/kubectl https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/kubectl.completion.bash
curl -o `brew --prefix`/etc/bash_completion.d/helm https://raw.githubusercontent.com/kubernetes/helm/master/scripts/completions.bash
curl -o `brew --prefix`/etc/bash_completion.d/git https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/git.completion.bash

curl -o `brew --prefix`/etc/bash_completion.d/nvm https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/nvm.completion.bash
curl -o `brew --prefix`/etc/bash_completion.d/npm https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/npm.completion.bash

# Environment Settings:
ln -s -f -v $BASEDIR/bash/.bash_profile ~/.bash_profile
ln -s -f -v $BASEDIR/bash/.inputrc ~/.inputrc

# AWS
curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py --user && rm get-pip.py
python -m pip install awscli --upgrade --user
